id: P008216
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:08:33.582473
source_metadata:
  id: bdr:W25185
  title: བཀའ་བརྒྱུད་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    0adb8fa717574d839d4a0ee6a67316c0:
      image_group_id: I5763
      title: ''
      volume_number: 1
      total_pages: 278
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
