id: I0A212BED
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:00:13+00:00'
last_modified: '2022-06-09T05:18:26.775576+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25185
  title: བཀའ་བརྒྱུད་ཞལ་འདོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2576':
      image_group_id: I5763
      title: ''
      total_pages: 278
      order: 1
      base_file: 2576.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
